Our Proposition is:

 Low-income countries are more affected by climate-related disasters than high-income countries

In [46]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
# Climate change measured in CO2 emissisons 

climate_change_data = pd.read_csv("climate-change-raw-2021.csv", skiprows = 4)
climate_change_data = climate_change_data.drop(columns="Indicator Name")
climate_change_data = climate_change_data.drop(columns="Indicator Code")
climate_change_data.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,50.776,50.761000,50.746000,50.730000,50.715000,50.700000,50.685000,50.670000,...,42.957000,42.990000,43.041000,43.108000,43.192000,43.293000,43.411000,43.546000,43.697000,NaN
1,Aruba,ABW,27525.000,28139.000000,28537.000000,28763.000000,28922.000000,29080.000000,29246.000000,29411.000000,...,44059.000000,44351.000000,44666.000000,44978.000000,45293.000000,45614.000000,45949.000000,46294.000000,46654.000000,NaN
2,Aruba,ABW,NaN,2.206183,1.404498,0.788835,0.551271,0.544810,0.569216,0.562594,...,0.543931,0.660561,0.707733,0.696090,0.697901,0.706219,0.731740,0.748028,0.774631,NaN
3,Aruba,ABW,54208.000,55434.000000,56234.000000,56699.000000,57029.000000,57357.000000,57702.000000,58044.000000,...,102565.000000,103165.000000,103776.000000,104339.000000,104865.000000,105361.000000,105846.000000,106310.000000,106766.000000,NaN
4,Aruba,ABW,NaN,2.236462,1.432843,0.823502,0.580334,0.573498,0.599694,0.590951,...,0.503385,0.583290,0.590508,0.541048,0.502860,0.471874,0.459266,0.437415,0.428017,NaN

In [ ]:
# GDP measured in current international dollars (PPP) per capita.

gdp = pd.read_csv(
    "GDP-Per_capita-ppp.csv",
    skiprows=4
)
gdp = gdp.drop(columns=gdp.columns[gdp.columns.str.startswith("Unnamed")])
gdp = gdp.drop(columns = "Indicator Name")
gdp = gdp.drop(columns = "Indicator Code")
gdp.head()
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 68 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  266 non-null    object
 1   Country Code  266 non-null    object
 2   1960          0 non-null      float64
 3   1961          0 non-null      float64
 4   1962          0 non-null      float64
 5   1963          0 non-null      float64
 6   1964          0 non-null      float64
 7   1965          0 non-null      float64
 8   1966          0 non-null      float64
 9   1967          0 non-null      float64
 10  1968          0 non-null      float64
 11  1969          0 non-null      float64
 12  1970          0 non-null      float64
 13  1971          0 non-null      float64
 14  1972          0 non-null      float64
 15  1973          0 non-null      float64
 16  1974          0 non-null      float64
 17  1975          0 non-null      float64
 18  1976          0 non-null      float64
 19  1977          0 non-null      float64
 20  1978          0 non-null      float64
 21  1979          0 non-null      float64
 22  1980          0 non-null      float64
 23  1981          0 non-null      float64
 24  1982          0 non-null      float64
 25  1983          0 non-null      float64
 26  1984          0 non-null      float64
 27  1985          0 non-null      float64
 28  1986          0 non-null      float64
 29  1987          0 non-null      float64
 30  1988          0 non-null      float64
 31  1989          0 non-null      float64
 32  1990          234 non-null    float64
 33  1991          234 non-null    float64
 34  1992          235 non-null    float64
 35  1993          235 non-null    float64
 36  1994          236 non-null    float64
 37  1995          238 non-null    float64
 38  1996          238 non-null    float64
 39  1997          240 non-null    float64
 40  1998          240 non-null    float64
 41  1999          240 non-null    float64
 42  2000          242 non-null    float64
 43  2001          242 non-null    float64
 44  2002          243 non-null    float64
 45  2003          243 non-null    float64
 46  2004          243 non-null    float64
 47  2005          243 non-null    float64
 48  2006          244 non-null    float64
 49  2007          245 non-null    float64
 50  2008          248 non-null    float64
 51  2009          249 non-null    float64
 52  2010          249 non-null    float64
 53  2011          249 non-null    float64
 54  2012          247 non-null    float64
 55  2013          248 non-null    float64
 56  2014          247 non-null    float64
 57  2015          247 non-null    float64
 58  2016          246 non-null    float64
 59  2017          247 non-null    float64
 60  2018          247 non-null    float64
 61  2019          247 non-null    float64
 62  2020          247 non-null    float64
 63  2021          247 non-null    float64
 64  2022          247 non-null    float64
 65  2023          245 non-null    float64
 66  2024          243 non-null    float64
 67  2025          233 non-null    float64
dtypes: float64(66), object(2)
memory usage: 141.4+ KB

In [ ]:
# Droughts, Floods, extreme temperatures (% of population, avg 1990-2009)
extreme_temp_data = pd.read_csv("API_EN.CLC.MDAT.ZS_DS2_en_csv_v2_9888.csv", skiprows = 4)
extreme_temp_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN